services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yaqoot_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - typesense
    networks:
      - yaqoot_net

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yaqoot_queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - yaqoot_net

  vite:
    image: node:18
    container_name: yaqoot_vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - yaqoot_net

  web:
    image: nginx:latest
    container_name: yaqoot_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - yaqoot_net

  db:
    image: mysql:8.0
    container_name: yaqoot_db
    restart: always
    environment:
      MYSQL_DATABASE: yaqoot_market
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yaqoot
      MYSQL_PASSWORD: yaqoot
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yaqoot_net

  typesense:
    image: typesense/typesense:27.1
    container_name: yaqoot_typesense
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: >
      --data-dir /data
      --api-key=typesense_local_key
      --listen-port=8108
      --enable-cors
    networks:
      - yaqoot_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yaqoot_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: yaqoot
      PMA_PASSWORD: yaqoot
    networks:
      - yaqoot_net

networks:
  yaqoot_net:

volumes:
  db_data:
  typesense_data:
